package chat.Shared;

public enum AuthencationResponse {
    LOGIN_SUCCESS,
    ALREADY_LOGGED_IN,
    REGISTERED,
    INVALID_USERNAME,
    INVALID_PASSWORD,
    REGISTER_PROCESS,
    USERNAME_EXISTS,
    PHONE_NUMBER_EXISTS
}
