package chat.Shared;

public enum AuthencationResponse {
    LOGIN_SUCCESS,
    ALREADY_LOGGED_IN,
    REGISTERED,
    INVALID_USERNAME,
    INVALID_PASSWORD,
    INVALID_PHONE_NUMBER,
    INVALID_NAME,
    USERNAME_EXISTS,
    PHONE_NUMBER_EXISTS,
    SERVER_ERROR
}
