package chat.Shared;

public enum ServerEvent {
    USER_JOINED,
    USER_DISCONNECTED,
    COMMAND_EXECUTED,
    WRONG_COMMAND,
    MESSAGE_RECEIEVED,
    CLIENTS_LIST_RECEIEVED,
    USER_PROFILE_RECEIEVED,
    COMMAND_WROTE_WRONG,
    SERVER_ERROR
}
